apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 32000
  selector:
    app: backend
  type: NodePort
